version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - contextcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefixes: github.com/kjuiop/live-platform-go

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck