version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - contextcheck
    - unused
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kjuiop/live-platform-go

run:
  timeout: 5m
